### ISSUE TITLE
🚁 Button feature request! 

### ISSUE THREAD

**Issue by Andorr** [cloutsoftware/compclout#7]
### 🛹 Introduction
The button-component is basically the most important component in this library, because it is the most frequently used and is a component that is really visible on websites. The button needs to look good, have different variations, colors, and sizes. Therefore, I have come with this feature request. Most of the request is to mimick the behavior that is used in the other projects. Especially look at [this](https://github.com/cloutsoftware/kvist/blob/dev/ui/src/components/base/Button/Button.js) component.

### 🚩 Wanted features
1. It should be possible to specify variants for the button as props. The wanted variants is:
   * _contained_ (normal - with background and shadow)
   * _outlined_ - (only a border)
   * _text_ - (no background and border)
   * _icon_ - (transparent and circular - look at [this](https://github.com/cloutsoftware/kvist/blob/master/ui/src/components/base/Button/Button.js)

2. Specify the color for the button as props. This should change and adapt based on the selected variant. 
3. Be able to _disable_ a button with a _disabled_-prop. This should make the button look disabled and not-clickable.
4. Have the possibility to disable shadow-styling in the _contained_ variant - using a _disableElevation_-prop. 
4. Have built-in functionality for showing a spinner next to the text - using a _loading_-prop. 
5. Have the functionality to be able to add _children_-elements inside the button-element. For example if one wants to add an icon inside the button, one can simply do this by adding an Icon manually as children in the button-component.

### 🌌 Examples

It would be nice if the button looked something like this:

#### Contained:
![image](https://user-images.githubusercontent.com/31648998/86043995-c3e27a80-ba49-11ea-9091-b6f12e3acb36.png)

#### Variant _text_:
![image](https://user-images.githubusercontent.com/31648998/86044055-d78de100-ba49-11ea-829e-bfdee124ac72.png)

#### Disabled:
![image](https://user-images.githubusercontent.com/31648998/86044123-f3918280-ba49-11ea-87dd-c815373c6347.png)

### 🏜 Sample usage
![image](https://user-images.githubusercontent.com/31648998/86044288-318ea680-ba4a-11ea-9193-e565e5c43457.png)

**Comment by williamaredal** [comment]
Started a new branch to implemet this.

**Comment by Andorr** [comment]
> Started a new branch to implemet this.

Perfect! 👍 Feel free to ask any questions if you are stuck or don't understand something 😛
